### ISSUE TITLE
Unable to handle objects that contain a `.` in their name

### ISSUE THREAD

**Issue by rquitales** [pulumi/pulumi-converter-kubernetes#3]
### What happened?

Any Kubernetes object that contains a `.` in their name will result in a conversion error. While Kubernetes recommends using DNS labels for names, using a dot is not strictly prohibited. Our converter fails as the intermediary PCL to target language fails with `Either a quoted string block label or an opening brace ("{") is expected here.`

We will need to sanitize the object name to ensure generation succeeds.

### Example

A valid pod resource:

```yaml
apiVersion: v1
kind: Pod
metadata:
  namespace: frontend
  name: nginx.pod
spec:
  containers:
    - name: nginx
      image: nginx:1.14-alpine
      resources:
        limits:
          memory: 20Mi
          cpu: 0.2
```

### Output of `pulumi about`

-

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
